### ISSUE TITLE
Possible incompatibility of license with LAMMPS

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/librascal#303]
librascal is distributed under the LGPL-v3 license, and LAMMPS under the GPL-v2 license. These two licenses are incompatible in the sense that if one redistribute code, they must do so under GPL-v3 license. Since LAMMPS is **not** distributed under `GPL-v2 or later` but `GPL-v2` license, this could make librascal incompatible with LAMMPS from a distribution standpoint (i.e. we could not distribute code using librascal inside the main LAMMPS repository without them changing the license to GPL-v3). For more information on compatibility see https://softwareengineering.stackexchange.com/q/238748.

Since it is much easier for us to change the license to LGPL-v2-or-later than for LAMMPS to change to GPL-v3 (this requires contacting all contributors and ensuring they agree to the license change), this might be a good thing to do on our side 😃.

----

As a side question, was there a reason that a copyleft (GPL/LGPL) license was picked instead of a permissive one (BSD/MIT)? I tend to prefer permissive licenses for libraries since that make them compatible with everything, which is usually the goal. I know some people strongly disagree with this!

**Comment by ceriottm** [comment]
Can we do "LGPL-v2 or later"?

**Comment by Luthaf** [comment]
Yes, I edited my initial message to suggest that.
