### ISSUE TITLE
SA-GPR predictions aren't rotationally covariant

### ISSUE THREAD

**Issue by kzinovjev** [lab-cosmo/librascal#398]
Hi,
I got some weird results while playing with the SA-GRP example [here](https://github.com/gabor1/chemrev-gpr/tree/main/water/water.ipynb) - when the input structures are rotated, the predicted vectors do not generally transform as expected. For a rotation around y axis all is good, but for others I get nonsensical results. Here's what I tried (just appended to the end of the notebook):
```python
def get_rot_matrix(angle, axis):
    c, s = np.cos(np.radians(angle)), np.sin(np.radians(angle))
    Rx = np.array([[1, 0,  0], 
                   [0, c, -s], 
                   [0, s,  c]])
    return np.roll(Rx, (axis, axis), (0, 1))

def rotate_data(fw, R):
    fw_rot = []
    for w in fw:
        w_rot = w.copy()
        # Rotate, keeping the coords within the cell
        w_rot.positions = (w.positions - 50) @ R.T + 50
        fw_rot.append(w_rot)
    return fw_rot

def get_ylpred(fw, lX_ref, wl):
    lX = lsoap.transform(fw).get_features(lsoap)
    lX = np.moveaxis(lX.reshape((lX.shape[0],-1,3)),2,1)[:,[2,0,1]]
    lK = f2v(v2f(lX) @ v2f(lX_ref).T)
    return f2v(v2f(lK) @ v2f(wl))

# Loop over x/y/z axes and a range of angles
for axis in range(3):
    for angle in range(0, 360, 60):
        R = get_rot_matrix(angle, axis)
        fw_rot = rotate_data(fw, R)
        ylpred = get_ylpred(fw_rot, lX[isparse], wlsparse)
        # Print the largest deviation between prediction for rotated structures
        # and rotated prediction for original structures
        print('xyz'[axis], angle, np.max(np.abs(ylpred_sparse @ R.T - ylpred)))
```
```
x 0 0.0
x 60 2.191014433571665
x 120 2.19101443357121
x 180 1.5491571039573586e-16
x 240 2.1910144335730286
x 300 2.191014433571665
y 0 0.0
y 60 8.640199666842818e-12
y 120 8.640199666842818e-12
y 180 6.95497134632593e-17
y 240 8.640199666842818e-12
y 300 8.640199666842818e-12
z 0 0.0
z 60 2.191014433580184
z 120 2.191014433582458
z 180 1.5612511283791264e-16
z 240 2.1910144335801838
z 300 2.191014433580184
```
So, it seems that for rotations around x or z axis the vectors do not transform covariantly with the structures. What am I missing? Thanks!

**Comment by ceriottm** [comment]
Try to rotate by multiplying on the left. I think it might be a matter of
handedness convention.

**Comment by kzinovjev** [comment]
@ceriottm thanks for a quick response! 
I'm applying the same transformation both to the coordinates and the vectors, so it shouldn't matter whether it's left or right, no?
But you're right, there indeed seems to be some issue with handedness - I tried to flip the sign for the y components of the features vector:
```python
lX = np.moveaxis(lX.reshape((lX.shape[0],-1,3)),2,1)[:,[2,0,1]]
lX[:,1] = -lX[:,1]  # Flipping the y components
```
both in the notebook code and in my `get_ylpred` function. And then all works well:
```
x 60 3.954891969470964e-11
x 120 4.0606185081060175e-11
x 180 1.5826861912022882e-16
x 240 3.9548697650104714e-11
x 300 3.954891969470964e-11
y 0 0.0
y 60 3.868616538227343e-11
y 120 3.8686387426878355e-11
y 180 1.5619009584427778e-16
y 240 3.868583231536604e-11
y 300 3.868616538227343e-11
z 0 0.0
z 60 3.6681435666707785e-11
z 120 3.668154668901025e-11
z 180 1.5619009584427778e-16
z 240 3.668121362210286e-11
z 300 3.6681435666707785e-11
```

**Comment by ceriottm** [comment]
So, in all honesty there was a terrible mess connected with the
Condon-Shortley convention so we cleaned that up for the spherical
expansion coefficients,
but kind of gave up for the covariant SOAP part - it works as long as you
are consistent, but if you aren't you are in for much pain.
Have a look at examples/equivariant_demo.py and examples/nice_demo.py that
show how to compute these things on the Python side.
This is what we have been using lately so it's much stabler and tested.
Let me know if it works for you or you need to access the covariants from
C++, which would be the only reason to prefer the
SphericalCovariants version.

**Comment by kzinovjev** [comment]
I don't need to access them from C++, but the performance is quite different:

**Comment by kzinovjev** [comment]
Ah, now it makes sense - I was puzzled by some inconsistencies between Spherical(In/Co)variants.
Thanks for the tip - using `SphericalExpansion` along with `compute_lambda_soap` works seamlessly! An added benefit is that I can get both invariant and covariant features from the same representation.
