### ISSUE TITLE
Is it possible to dump/display a SOAP-encoded atom as a vector of floats? [question]

### ISSUE THREAD

**Issue by UnixJunkie** [lab-cosmo/librascal#408]
I gave it a try, but it prints me things like:
```
<rascal.lib._rascal._internal.Strict_CenterContribution_NeighbourList_Centers.Center object at 0x7feec24ba030>
[...]
```
I was expecting a vector of floats.

My trial can be seen here:
https://github.com/UnixJunkie/librascal/blob/SOAP_test_01/soap_test.py

**Comment by Luthaf** [comment]
Yes, you need to do something like this:

```py
molecules = ase_read(input_fn, "{}:{}".format(start, start + length))
soap_encoded_molecules = soap.transform(molecules)

soap_np_array = soap_encoded_molecules.get_features(soap)
```

This gives you a `n_atoms x n_features` numpy array.

**Comment by Luthaf** [comment]
There are a handful more function to get the gradients of the representation, or some metadata describing the rows of the returned array.

https://github.com/lab-cosmo/librascal/blob/fed28b910d9ba6f8549c935aaf67bdc14051d511/bindings/rascal/neighbourlist/structure_manager.py#L117-L204

The columns of the returned array are described by `soap.get_feature_index_mapping()`
