### ISSUE TITLE
Installing on CentOS Linux: CMake Error at cmake/rascalTools.cmake:141

### ISSUE THREAD

**Issue by AdamCoxson** [lab-cosmo/librascal#422]
Hi, 

I'm trying to install the NICE package onto a linux based cluster system, but the installation fails at pip install . of librascal-master. It works up until the error message provided below. CMake error 141, something to do with downloading wigxjpf, may be related to [this issue].(https://github.com/lab-cosmo/librascal/issues/413 ).

Desktop:
Ubuntu 20.04.5 LTS
conda V 22.11.0
python V 3.9.12

Cluster:
CentOS Linux 7
conda V 23.1.0
python V 3.9.12

I have gotten librascal installed on my Ubuntu 20.04 desktop distribution (a different machine which has rather limited RAM), but the same process fails on the CentOS linux dsitribution on my computer cluster. The conda environments on both distributions are nearly identical except for the CentOS environment not having the librascal/nice pkgs installed and also a slightly newer version of conda. (I will try to reinstall with 22.11.0 to see if that is the issue but not sure).

Any ideas or anyone come across this issue themselves?

> Building wheels for collected packages: rascal
>   Building wheel for rascal (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Building wheel for rascal (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [72 lines of output]
>       
>       
>       --------------------------------------------------------------------------------
>       -- Trying 'Ninja' generator
>       --------------------------------
>       ---------------------------
>       ----------------------
>       -----------------
>       ------------
>       -------
>       --
>       Not searching for unused variables given on the command line.
>       -- The C compiler identification is GNU 11.2.0
>       -- Detecting C compiler ABI info
>       -- Detecting C compiler ABI info - done
>       -- Check for working C compiler: /mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/cc - skipped
>       -- Detecting C compile features
>       -- Detecting C compile features - done
>       -- The CXX compiler identification is GNU 4.8.5
>       -- Detecting CXX compiler ABI info
>       -- Detecting CXX compiler ABI info - done
>       -- Check for working CXX compiler: /usr/bin/c++ - skipped
>       -- Detecting CXX compile features
>       -- Detecting CXX compile features - done
>       -- Configuring done
>       -- Generating done
>       -- Build files have been written to: /mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_cmake_test_compile/build
>       --
>       -------
>       ------------
>       -----------------
>       ----------------------
>       ---------------------------
>       --------------------------------
>       -- Trying 'Ninja' generator - success
>       --------------------------------------------------------------------------------
>       
>       Configuring Project
>         Working directory:
>           /mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-build
>         Command:
>           /tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /mnt/lustre/users/acoxson/external_models/NICE/librascal-master -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/python -DPYTHON_INCLUDE_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/include/python3.9 -DPYTHON_LIBRARY:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/python -DPython_ROOT_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2 -DPython_INCLUDE_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/include/python3.9 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/python -DPython3_ROOT_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2 -DPython3_INCLUDE_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/include/python3.9 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DINSTALL_PATH:STRING=/mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-install -DBUILD_EXAMPLES:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=Release
>       
>       -- Build type is: Release
>       -- Downloading wigxjpf
>       CMake Error at cmake/rascalTools.cmake:141 (message):
>         Something went wrong (1) during the download process of wigxjpf check the
>         file
>         /mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-build/third-party/wigxjpf-download/configure-error.log
>         for more details
>       Call Stack (most recent call first):
>         cmake/wigxjpf.cmake:5 (download_external_project)
>         cmake/rascalTools.cmake:208 (include)
>         CMakeLists.txt:70 (add_external_package)
>       
>       
>       -- Configuring incomplete, errors occurred!
>       See also "/mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
>       Traceback (most recent call last):
>         File "/tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 634, in setup
>           env = cmkr.configure(
>         File "/tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 332, in configure
>           raise SKBuildError(
>       
>       An error occurred while configuring with CMake.
>         Command:
>           /tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /mnt/lustre/users/acoxson/external_models/NICE/librascal-master -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/python -DPYTHON_INCLUDE_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/include/python3.9 -DPYTHON_LIBRARY:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/python -DPython_ROOT_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2 -DPython_INCLUDE_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/include/python3.9 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/python -DPython3_ROOT_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2 -DPython3_INCLUDE_DIR:PATH=/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/include/python3.9 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-zn0vbe7q/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DINSTALL_PATH:STRING=/mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-install -DBUILD_EXAMPLES:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=Release
>         Source directory:
>           /mnt/lustre/users/acoxson/external_models/NICE/librascal-master
>         Working directory:
>           /mnt/lustre/users/acoxson/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.9/cmake-build
>       Please see CMake's output for more information.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for rascal
> Failed to build rascal
> ERROR: Could not build wheels for rascal, which is required to install pyproject.toml-based projects

The file wigxjpf-download/configure-error.log just has:

> CMake Error at CMakeLists.txt:3 (project):
>   Running
> 
>    '/tmp/pip-build-env-f3fp87qw/overlay/bin/ninja' '--version'
> 
>   failed with:
> 
>    No such file or directory

**Comment by agoscinski** [comment]
Maybe the connection with the wigxjpf was just unstable for the moment? When I tried to manual download the package, the download got stuck once, so I can see that a connection time out being the reason for this.

You can try to manual download wigxjpf. In the librascal folder (remove build folder if it was created)
```
mkdir -p build/external
cd build/external
wget http://fy.chalmers.se/subatom/wigxjpf/wigxjpf-1.9.tar.gz
tar -xf wigxjpf-1.9.tar.gz
mv wigxjpf-1.9 wigxjpf
cd ..
ccmake ..
# you press c two times and then g
make
```
You might need to uncomment this code
https://github.com/lab-cosmo/librascal/blob/f5f65ea592b161297f84a0e173f546bbb56dc5f6/cmake/wigxjpf.cmake#L5-L11
so it does not download the project again.

**Comment by Luthaf** [comment]
This is a different error from the usual wigxjpf issue, we are now downloading wigxjpf from github (and not chalmers.se) since #412.

The error points to ninja not being available, but it should be installed by pip before starting librascal build:
https://github.com/lab-cosmo/librascal/blob/f5f65ea592b161297f84a0e173f546bbb56dc5f6/pyproject.toml#L2

Since you are mentioning a cluster, do you know which filesystem is used for `/tmp`? You could also try to set `TMPDIR` to another path and try again, maybe something like 

```bash
export TMPDIR=$HOME/tmp-librascal
# use the one below to install just librascal or replace it with the nice install command
pip install git+https://github.com/lab-cosmo/librascal
```

**Comment by AdamCoxson** [comment]
@agoscinski , 
I wasn't sure where I was meant to make the build/external directory. I've assumed you meant the folder called "librascal-master/_skbuild/linux-x86_64-3.10/cmake-build/external" ??

I deleted the wigxjpf folder found in "librascal-master/_skbuild/linux-x86_64-3.10/cmake-build/external"
Then downloaded wigxjpf following your steps.
After mv wigxjpf-1.9 wigxjpf I did "cd .." which took my cwd to cmake-build.
Running ccmake .. caused the below error to come up

> CMake Error: The source directory "/users/acoxson/sharedscratch/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.10" does not
>  appear to contain CMakeLists.txt.
>  Specify --help for usage, or press the help button on the CMake GUI.

I also tried the cmake ..  command in ~/cmake-build/external and ~/cmake-build/build, which came up with the option list, but when selecting [c] to configure, the below error came up.

>  Build type is: Release
>  CMake Error at /users/acoxson/sharedscratch/external_models/NICE/librascal-master/CMakeLists.txt:25 (project):
>    Running
> 
>     '/tmp/pip-build-env-xpekgf4t/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja' '--version'
> 
>    failed with:
> 
>     No such file or directory
> 
>  Configuring incomplete, errors occurred!
>  See also
>  "/users/acoxson/sharedscratch/external_models/NICE/librascal-master/_skbuild/linux-x86_64-3.10/cmake-build/CMakeFiles/CMakeOutput.log".

So I'm not sure whats going on, but a problem with ninja as @Luthaf pointed out? The file system for sharedscratch is lustre, I extracted librascal-master to a different folder on a login node. Trying pip install . to my nice_env conda environment did not work either, although it gave a different error.


>       cc1plus: all warnings being treated as errors
>       ninja: build stopped: subcommand failed.
>       Traceback (most recent call last):
>         File "/tmp/pip-build-env-3pen8sle/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 642, in setup
>           cmkr.make(make_args, install_target=cmake_install_target, env=env)
>         File "/tmp/pip-build-env-3pen8sle/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 679, in make
>           self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
>         File "/tmp/pip-build-env-3pen8sle/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 710, in make_impl
>           raise SKBuildError(
>       
>       An error occurred while building with CMake.
>         Command:
>           /tmp/pip-build-env-3pen8sle/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
>         Install target:
>           install
>         Source directory:
>           /users/acoxson/librascal-master
>         Working directory:
>           /users/acoxson/librascal-master/_skbuild/linux-x86_64-3.10/cmake-build
>       Please check the install target is valid and see CMake's output for more information.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for rascal
> Failed to build rascal
> ERROR: Could not build wheels for rascal, which is required to install pyproject.toml-based projects

**Comment by AdamCoxson** [comment]
Hi, just wondering how far along this has come?

Also, @Luthaf how can I download and install the version from your branch as the link gives 404 error? I suppose through some linux commands like with the main librascal branch?

**Comment by agoscinski** [comment]
#423 has already been merged. It should work now (or at least fail because of a different reason)

**Comment by AdamCoxson** [comment]
I deleted the old librascal-master folder. Downloaded and unzipped the repo and performed "pip install ."

The first time I get an error with large output. 
Running the same command a second time gives a much smaller error, which is the Cmake 141 error again.
[librascal_error_1st_run.txt](https://github.com/lab-cosmo/librascal/files/11029153/librascal_error_1st_run.txt)
[librascal_error_2nd_run.txt](https://github.com/lab-cosmo/librascal/files/11029152/librascal_error_2nd_run.txt)

**Comment by Luthaf** [comment]
The first error is related to C++14 support: you are using g++ 4.8.5 (from 2015), which only supports (part of) the C++11 standard. Can you use a module to load a more recent compiler? This output is a bit strange, since you are also using gcc version 11:

```
      -- The C compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 4.8.5
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
```

Maybe you can set the CXX environement variable to `/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/g++` or `/mnt/lustre/users/acoxson/anaconda3/envs/nice_env2/bin/c++` (check if one of them exist first)?

Before building the code again, make sure to remove the `_skbuild` folder inside `librascal-master`.

**Comment by AdamCoxson** [comment]
That seemed to be the main issue!

I added this to my environment
conda install -c conda-forge cxx-compiler

The installation was a success. I will test it out a bit more tomorrow, then I will let you know the outcome and close this issue.

**Comment by AdamCoxson** [comment]
Its working now. 

I guess the main issue was that the conda install of gcc didn't install up to date versions of g++, so conda install -c conda-forge cxx-compiler may be another package requirement for specific OS cases.  I can't confirm but suspect the wigxjpf problem was likely just a symptom of this.

Thanks guys for the help! :)

Closing this

**Comment by mahrossi** [comment]
Hello, I get the same error reported here, with a current version (everything downloaded today).

CMake Error at CMakeLists.txt:3 (project):
  Running

   '/cobra/ptmp/mrossi/pip-build-env-rc5akfaa/overlay/bin/ninja' '--version'

  failed with:

   No such file or directory 
   
   
P.S.: This error is happening in my computer (Mac) and 3 linux cluster machines. I tried different installations, different compilers - same. Feels like there is some bad interaction and the error is not informative.

P.P.S.: This also means that we cannot use this in our systems at least after spending 3 hours to install ;-) IDK, maybe there is some safer environment to install this that avoids this error? and this could be distributed?

**Comment by Luthaf** [comment]
After a direct discussion with @mahrossi, we found out the issue was an outdated `_skbuild` cache, and #430. Anyone having the same problem when trying to build from a clone should try removing the `_skbuild` directory and run `pip install` again.
